services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: andika-frontend

    restart: unless-stopped

    ports:
      - "4173:4173"

    networks:
      - andika-network


networks:
  andika-network:
    external: true
    name: andikacatering-api-main_andika-network
